services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www

    db:
        image: mysql:8.0
        container_name: laravel-db
        restart: unless-stopped
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
        restart: unless-stopped

    nginx:
        image: nginx:alpine
        container_name: laravel-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/

#    queue:
#        build:
#            context: .
#            dockerfile: Dockerfile
#        container_name: laravel-queue
#        restart: unless-stopped
#        working_dir: /var/www
#        volumes:
#            - ./:/var/www
#        command: php artisan queue:work --tries=3 --sleep=3
#        depends_on:
#            - app
#            - db

volumes:
    db_data:
